### ISSUE TITLE
TwiiterComposer dismissing my view controller (iOS)

### ISSUE THREAD

**Issue by vanitaladkat** [twitter/twitter-kit-ios#16]
Me and many like me are facing issue of dismissing of Presenting View controller automatically for error in case of login. 
Issue is reported by many, check that [here](https://twittercommunity.com/t/twitterkit-is-dismissing-callee-controller-in-airplane-mode/93239) : https://twittercommunity.com/t/twitterkit-is-dismissing-callee-controller-in-airplane-mode/93239.

Even in case of user cancels login.

**Comment by robhedgehog** [comment]
I am also experiencing the same problem 🙁

**Comment by inamiy** [comment]
https://github.com/twitter/twitter-kit-ios/pull/23 might possibly fix this issue.

**Comment by rajul-arora** [comment]
A similar fix has been made internally and will be part of the next version of TwitterKit 👍

**Comment by robhedgehog** [comment]
Thanks Rajul, is there a rough ETA on when this version may be released?

**Comment by forzakmah** [comment]
I am also having the same issue.

**Comment by bill350** [comment]
@rajul-arora Could you make a new version with this fix, please 🙏

**Comment by JacobJT** [comment]
Since Twitter seems to not really give a crap about fixing major issues in anything close to a timely manner, do any of you have a workaround?

**Comment by SebastianKumor** [comment]
So when is the new version of twitterkit going out ?

**Comment by sandervandenbrink** [comment]
For anyone not wanting to use a fork on the Twitter SDK I made a workaround to prevent the dismiss on your view controller https://github.com/sandervandenbrink/twitter-dismiss-workaround-ios
