### ISSUE TITLE
TwitterKit iOS - Signing - Stoped working. 

### ISSUE THREAD

**Issue by angelbetancourt** [twitter/twitter-kit-ios#17]
I've TwitterKit integrated, followed all necessary settings mentioned in the Twitter dev notes, including the info.plist settings and the url handle on app delegate, and about this one, it's always returning false when I call `- (void)logInWithViewController:(nullable UIViewController *)viewController completion:(TWTRLogInCompletion)completion;`:

`@nonobjc @available(iOS 9.0, *) 

    func application(_ application: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any])
        -> Bool {
            
            return TWTRTwitter.sharedInstance().application(application, open: url, options: options)
    }
    
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        
        return TWTRTwitter.sharedInstance().application(application, open: url, options: [:])
    }`

The given url seems to be ok `twitterkit-apcczt4diguk6myh6f0i*****://callback?app=ApccZt4dIgUk6Myh6f0ibvYl9&oauth_token=enKsAgAAAAAAytGCAAABYPrD_Mo&oauth_verifier=1qDr0xNr2O5eFLtOBzCt2yFl76IWFFzM`

and the app gets stuck here: 

![screen shot 2018-01-15 at 12 23 45 pm](https://user-images.githubusercontent.com/22026727/34955021-a0c7fcee-f9f0-11e7-989c-0dfad8d98beb.png)

Twitter App is installed and my account signed in

iPhone 7 Plus - iPhone 6s - 
iOS 11.2.1
Using TwitterCore (3.1.0)
Using TwitterKit (3.3.0)
Twitter App 7.14

**Comment by zapjonny** [comment]
I might be seeing the same or a similar problem.

`TWTRSession` always return nil on userName, authToken, authTokenSecret - even for TWTRSession objects retrieved using `TWTRTwitter.sharedInstance().sessionStore.existingUserSessions()`.

Looks like I will have to go back from TwitterKit 3.3.0 to previous version. Current one is too buggy.

**Comment by deffs** [comment]
I would try returning true instead of returning the sharedInstance

```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        
        TWTRTwitter.sharedInstance().application(app, open: url, options: options)
        
        return true
    }
```
This is working in my use case

**Comment by angelbetancourt** [comment]
@zapjonny did you solve it? what versions can I use? This still doesn't work.

**Comment by zapjonny** [comment]
@angelbetancourt I went back to the previous version.

**Comment by ksenia-lyagusha** [comment]
Hey guys, you'd better use version
pod 'TwitterKit', '~> 3.1.1'
this one more stable.
