### ISSUE TITLE
Demo app crashes on start

### ISSUE THREAD

**Issue by maziyarpanahi** [twitter/twitter-kit-ios#2]
**Bug Report**

Following the instruction of how to run the Demo, the app crashes on start with this error:

```
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

* Steps to reproduce the problem:
* iOS Version: 11.2
* XCode: Version 9.2 (9C40b)
* iOS Device Model: iPhone simulator
* TwitterKit/TwitterCore Version Number: latest

**Comment by rajul-arora** [comment]
Hey you need to set the consumer key and secret in the xcconfig and reload Xcode!

**Comment by maziyarpanahi** [comment]
Hi,
I did that before I open the XCode. I rename the sample, and put my key/secret inside. (I left the third one for ad empty)

**Comment by rajul-arora** [comment]
I remember seeing issues with this before but I noticed after cleaning and building (and restarting XCode) it eventually worked. 

Could you breakpoint in the AppDelegate and tell me if the values for the consumer key and secret are what you expect it to be (don't worry about posting the actual result here). 

Turning on exception breakpoints and seeing where the app crashes would also help me a lot!

**Comment by Duncun76918** [comment]
Hey

**Comment by maziyarpanahi** [comment]
Hi @rajul-arora,

I did clean, closed and re-opened the project and it worked perfectly. 
Many thanks mate 👍
