### ISSUE TITLE
Multiple iOS app uses same Twitter App for Login

### ISSUE THREAD

**Issue by mustafaozdemir** [twitter/twitter-kit-ios#21]
Our company has a framework that uses TwitterKit. 
All of our iOS apps are using this framework.
Our aim to doing this to manage users in only one Twitter Application.

I implemented this framework to all of our apps

When I try to Login with Twitter from Application B, it redirects to Twitter iOS application. 
Twitter asks me "Do you want to give permission to Application B ?"

After I accept the permission, Twitter App redirects to Application A.
But it should redirect me to Application B.

I am using Twitter iOS Application in my iPhone 6S Plus
iOS version: 11.2.2
Twitter iOS App version : 7.15
TwitterKit version 3.3.0
TwitterCore version 3.1.0

**Comment by efrohnhoefer** [comment]
This isn't supported. You should use different consumer key/secret for each app.

**Comment by ahmadsallam** [comment]
@mustafaozdemir did you solve the problem ?

**Comment by mustafaozdemir** [comment]
@ahmadsallam no I didn't. To solve this I have used old TwitterKit version in my projects.
When you press login, it redirects to safari instead of Twitter iOS app, and then it redirects back to the correct application.

**Comment by ahmadsallam** [comment]
Many thanks 🙏 my friend
