### ISSUE TITLE
:'TwitterKit/TWTRKit.h' file not found"   ?为什么#import <TwitterKit/TWTRKit.h>在模拟器上编译不报错,在真机上编译就提示not found file?

### ISSUE THREAD

**Issue by CG-Kerr** [twitter/twitter-kit-ios#25]
为什么#import <TwitterKit/TWTRKit.h>在模拟器上编译不报错,在真机上编译就提示not found file?
my problem is that when I use run my project on Simulator,it's ok ;but when i run my project on my phone ,#import <TwitterKit/TWTRKit.h>,then alert :'TwitterKit/TWTRKit.h' file not found" ,did anybody meet the same issue?

**Comment by deffs** [comment]
Use `import TwitterKit` instead and it should work in Swift

**Comment by riazhazan** [comment]
I tried `import TwitterKit` but still no luck. I am running in Xcode 9

**Comment by katejlee** [comment]
Not enough information, and can't reproduce.
