### ISSUE TITLE
Fetch details of followers and following users ? 

### ISSUE THREAD

**Issue by faisalazeez** [twitter/twitter-kit-ios#26]
Will I be able to fetch details of followers and following users like phone number, email etc ?

**Comment by andypiper** [comment]
This is more of a general Twitter API question. There is no built-in functionality in Twitter Kit to enable this, but you can use the [TwitterAPIClient](https://github.com/twitter/twitter-kit-ios/wiki/Access-Twitter's-REST-API) to find friends and followers. There's no ability in the Twitter API to get any phone numbers. Email is accessible if the authenticated user has chosen to make it available to the application (see ["Request user email address"](https://github.com/twitter/twitter-kit-ios/wiki/Log-In-With-Twitter))

**Comment by stancho-dynoden** [comment]
@andypiper your answer does not give details for getting the followers and following emails. Request user email address is only for the current user, or I misunderstand what you said. I have checked this - GET friends/list but this does not return the users' email addresses.

**Comment by andypiper** [comment]
You're correct, the API does not provide that information unless you are the authenticated / current user. Closing this as this is not a Twitter Kit issue.
