### ISSUE TITLE
How to share session among app and sharedextention(SLComposeServiceViewController)

### ISSUE THREAD

**Issue by srinadh-ispace** [twitter/twitter-kit-ios#27]
This form is for reporting issues in the Twitter Kit Android library. For all other developer questions/issues about Twitter please visit [Twitter Community](https://twittercommunity.com/).

**Bug Report**

We work constantly to fix bugs, tweak functionality and improve device support. Providing detailed feedback will help us to quickly resolve your issue.

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
* * Expected behavior:
* * iOS Version (eg. iOS 10.2):
* * iOS Device Model (eg. iPhone 6):
* * TwitterKit/TwitterCore Version Number:

* **Feature Request**
*
* If you have anything you'd like to contribute, we recommend discussing it with the core team before writing it.
*
* * Describe feature in as much detail as possible:
* * Include sample usage where appropriate:

**Comment by katejlee** [comment]
Not enough information
