### ISSUE TITLE
Swift Usage

### ISSUE THREAD

**Issue by JesseNoBata** [twitter/twitter-kit-ios#35]
import TwitterKit with the following: 

    TWTRTwitter.sharedInstance().start(withConsumerKey:"hTpkPVU4pThkM0", consumerSecret:"ovEqziMzLpUOF163Qg2mj")

produces error "Use of unresolved identifier 'TWTRTwitter'

**Comment by Gabriel-Lewis** [comment]
Make sure you import TwitterKit

**Comment by JesseNoBata** [comment]
I have that line : import TwitterKit

Compiler still says Use of" Unresolved identifier "-->Did you mean TWRTweetView'

The install page talks about a bridging header, but no pop-up in xcode shows up when importing TwitterKit

**Comment by Gabriel-Lewis** [comment]
Which version are you on? Previous versions used ‘Twitter’ instead of TWTRTwitter’

**Comment by JesseNoBata** [comment]
My podfile.lock displays:

**Comment by aizatomar** [comment]
This is not the latest version. The latest version is 3.3.0. If you had not declare any optimistic versioning in your Podfile (eg: `pod 'TwitterKit', '~> 2.8.0'`), you can just do `pod update TwitterKit`. You should see on your Terminal that the pod will be updated from 2.8.1 to 3.3.0. Cheers.

**Comment by evansobkowicz** [comment]
Please upgrade to the recent 3.4.0 release and let us know if this is still an issue.
