### ISSUE TITLE
SDK methods and flow

### ISSUE THREAD

**Issue by OhadMaor-VIA** [twitter/twitter-kit-ios#36]
**Bug Report - latest TwitterKit to this date**
1. **The whole flow doesn't work:** 
> If Twitter is not installed on the device it automatically falls back to use OAuth via a web view (using SFSafariViewController for the first user, and a UIWebView for subsequent additional users.)

Using iOS 11, on iPhone X/6S.

**What works:**
Only if the user has Twitter app installed we can compose a twit or log-in - the rest just **doesn't** work (app isn't installed): 

- When using `composer.show(from: self) { (result) in` I am getting `.cancelled`.
- When using `TWTRTwitter.sharedInstance().logIn(completion: { (session, error) in` I am getting _Request failed: unauthorized (401)_

_Note_: Session remains even if you delete the Twitter app and of course, compose action still works.
_Note2_: `SafarServices` is embedded inside the project but it doesn't really matter because UIWebView flow should work and it doesn't.

Also,
> NOTE: TWTRComposer relies on the existence of a local Twitter account in current session. If no account exists, attempting to show the composer will prompt the user to log in to Twitter app or on a web view.

"web view" flow doesn't work, again, only when Twitter app is installed

## SOLVED 1:

> Although the callback URL will not be requested by Twitter Kit in your app, it must be set to a valid URL for the app to work with the SDK.

even though when you try to create a Twitter app it doesn't say it is mandatory - **which it is** if you want above flow will work.

2. If API key/secret are invalid, any action performed by TwitterKit lead to app crash - to avoid a crash do I need to always validate `TWTRTwitter.sharedInstance().sessionStore.session()` ? Isn't that something that should be encapsulated inside the SDK ?

3. Once we instantiate the singleton using the `start("key", "secret")` method, the project plist with the value:  `twitterkit-{API KEY}` has no meaning because once we change that value everything will still work the same (given start method key and secret are correct). What's the point of the double key ?

**Comment by OhadMaor-VIA** [comment]
We have decided to abandon the TwitterKit SDK.

**Comment by JacobJT** [comment]
This was an issue prior to the 3.4.0 release. We had no good way around it other than a `if (UIApplication.shared.canOpenURL(URL(string:"twitter://")!))`. I feel like that's not something that should be on the developers to do, seems like something that should be built into the SDK, though I know that's unlikely to happen.

Does Twitter have any suggestions if literally all we want in our app is a social share for sharing ones referral code? I don't need all the oauth, other than how it makes me sing in to post of course. But I would love just a simple tool that let's my users share a promo code with a couple taps.
