### ISSUE TITLE
Invisible Cancel and Tweet Button

### ISSUE THREAD

**Issue by ankittlp** [twitter/twitter-kit-ios#38]
**Bug Report**

I am using TWTRComposerViewController to show tweet controller with initial text and video url, where every thing is expected to work file but I see cancel button and Tweet buttons are invisible.

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
* * Expected behavior:
* * iOS Version : 11.0.2
* * iOS Device Model : iPhone 7
* * TwitterKit/TwitterCore Version Number: 3.3.0
![img_0689](https://user-images.githubusercontent.com/919529/37061797-94142b2a-21ba-11e8-9c80-2284190f3ecf.PNG)

**Comment by evansobkowicz** [comment]
Please try upgrading to 3.4.0 and let us know if you're still experiencing this issue.
