### ISSUE TITLE
Unexpected behaviour when dismissing authentication modal from another modal.

### ISSUE THREAD

**Issue by chriscdn** [twitter/twitter-kit-ios#40]
Unexpected behaviour when dismissing authentication modal from another modal.

### Expected behavior

Within my app I present a modal view controller.  From this controller I call `logInWithViewController:completion:` to present the Twitter authentication modal.  If I tap `Done` it should only dismiss the Twitter authentication modal.

### Actual behavior

Tapping `Done` dismisses the Twitter authentication modal *and* my modal view controller.  It should only dismiss itself.

### Steps to reproduce the behavior

- Present a modal view controller by calling `presentViewController:controller:animated:completion:`
- From within that modal call the Twitter `logInWithViewController:completion:` method and pass the modal view controller to the method
- Tap `Done`

**Comment by chriscdn** [comment]
I traced through the source and couldn't find why the behaviour is inconsistent.  Either way, I worked around it by adding the following to the presenting view controller:

	-(void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^)(void))completion {
		UIViewController *presentedViewController = self.presentedViewController;
		[presentedViewController dismissViewControllerAnimated:flag completion:completion];
	}

**Comment by neilDistill** [comment]
@chriscdn, thank you for posting this work around.

In my case, I had to add the override to a UINavigationController subclass with a property I called "isDismissalBlockEnabled" so I could enable/disable this behaviour.

<pre><code>
-(void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^)(void))completion {
    if (self.isDismissalBlockEnabled) {
        UIViewController *presentedViewController = self.presentedViewController;
        [presentedViewController dismissViewControllerAnimated:flag completion:completion];
        return;
    }
    
    [super dismissViewControllerAnimated:flag completion:completion];
}
</code></pre>

**Comment by chiragpurohit71085** [comment]
I am facing the same issue.

**Comment by evansobkowicz** [comment]
We merged a [fix](https://github.com/twitter/twitter-kit-ios/pull/12) for `logInWithViewController` in the 3.4.0 release. Please try upgrading and let us know if this issue is not resolved.

**Comment by lvchangye** [comment]
I use swift  TwitterKit 3.4.2, also have this issue
