### ISSUE TITLE
TWTRTimelineViewController impossible to dismiss image

### ISSUE THREAD

**Issue by mannycalavera27** [twitter/twitter-kit-ios#41]
TWTRTimelineViewController impossible to dismiss image

### Expected behavior

Tap on single tweets' image -> show image in modal view -> dismiss tapping on "X" button

### Actual behavior

It's impossible to tap on "X" because of UI issue:

![simulator screen shot - iphone x - 2018-03-09 at 12 36 41](https://user-images.githubusercontent.com/4839857/37205836-94730cac-2396-11e8-94b3-93d8494a9f7d.png)

### Steps to reproduce the behavior

Tap on single tweets' image

**Comment by nbonamy** [comment]
+1 even in single tweet display

**Comment by jessedijkstra** [comment]
+1 even less clear on a white bar

**Comment by walsht** [comment]
+1, anyway we can adjust that close image color?

**Comment by katejlee** [comment]
The patch to fix this issue has been added to internal repo. We will be releasing final version in next few weeks.
