### ISSUE TITLE
TWTRTimelineView instead of ViewController

### ISSUE THREAD

**Issue by mindylou** [twitter/twitter-kit-ios#43]
I'm working on a news app and would love to embed Twitter's `TWTRTimelineViewController` into a `UIScrollView` or `UITableView`.  Would it be possible to add this to TwitterKit?

### Expected behavior

I want to embed Twitter's Timeline `TableView` into another view with other `UIViews`.

### Actual behavior

Right now TwitterKit only supports the `TableViewController` for displaying timelines, so my app currently pushes a `TWTRTimelineViewController` on top of the article view. This detracts from the user experience. 

### Steps to reproduce the behavior

N/A

**Comment by qiaoyan** [comment]
try this (Implementing a Custom Container View Controller) : https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html
