### ISSUE TITLE
No member 'tweetView'

### ISSUE THREAD

**Issue by kevcol** [twitter/twitter-kit-ios#47]
I've installed TwitterKit via Cocoapods following the [installation instructions](https://github.com/twitter/twitter-kit-ios/wiki/Installation).  I have "Import TwitterKit" in my file and I believe my bridging header is OK.  But the sample code to show tweets gives me an error.

The code:

 ```
 func loadTweets() {
    let client = TWTRAPIClient()
    client.loadTweet(withID: "20") { (tweet, error) in
      if let t = tweet {
        self.tweetView.configure(with: t)
      } else {
        print("Failed to load Tweet: \(error.localizedDescription)")
      }
    }
  }
```

The error: 
"Value of type 'Setup' has no member 'tweetView'" 

![setup_swift_ _edited](https://user-images.githubusercontent.com/727443/37742960-21c72704-2d25-11e8-8d1c-4a2746d98428.png)

### Expected behavior

To be able to configure tweetview

### Actual behavior

"Value of type 'Setup' has no member 'tweetView'" 

### Steps to reproduce the behavior
I followed these steps to set-up (Cocoapods): https://github.com/twitter/twitter-kit-ios/wiki/Installation
I followed these steps to show tweets: https://github.com/twitter/twitter-kit-ios/wiki/Show-Tweets

**Comment by rajul-arora** [comment]
You need to create your own tweet view using the `TWTRTweetView` class and add it as a subview to your view controller (or wherever you plan to display the tweet). The wiki was not clear and the code snippet has been updated to reflect this.
