### ISSUE TITLE
TWTRCompose doesn't store session after signing in - endless loop of signing in / granting permissions instead

### ISSUE THREAD

**Issue by JacobJT** [twitter/twitter-kit-ios#49]
After logging in / granting permissions via TWTRCompose, no session is stored / available

### Expected behavior

Logging in / granting permissions via TWTRCompose will create a session, so when I try to show the window, I'll be able to send a tweet.

### Actual behavior

Trying to open the TWTRCompose only opens Twitter and asks me to grant permissions, over and over again.

### Steps to reproduce the behavior

Show a TWTRCompose. Log in / accept permissions.  
Try to press the tweet button again to actually send the tweet, and instead go right back to the permissions page

**Comment by JacobJT** [comment]
I'll note - the ONLY Twitter functionality I'm looking for in my app is a referral share via Tweet. I'm not trying to use Twitter as authentication or anything. Considering that this TWTRCompose can detect no signed in user and take me to the app to authenticate it, why is it not able to do anything with that action? It seems to me once that login / accepting permissions is completed, it should return me to my app *and* show the TWTRCompose I was trying to open in the first place.

What are the proper steps to do this, if not signing in / accepting permissions, then opening the compose again?

**Comment by sushinoya** [comment]
Facing the exact same issue. Would appreciate some help here :)

**Comment by JacobJT** [comment]
@sushinoya , You have to use the API to explicitly check for logged in users and otherwise login.  Here's a snippet when my Twitter Share button is pressed, where `displayTweet()` is a method that sets up the `TWTRComposer`
```
if( TWTRTwitter.sharedInstance().sessionStore.hasLoggedInUsers() ) {
    self.displayTweet()
} else {
    TWTRTwitter.sharedInstance().logIn(completion: { (session, error) in
        if( session != nil ) {
            self.displayTweet()
        } else {
            self.presentSimpleAlert(withTitle: "Error", message: "There was an error trying to login to Twitter: \(String(describing: error?.localizedDescription))")
        }
    })
}
```

**Comment by sushinoya** [comment]
@JacobJT, thanks for the reply. Although I am already doing that. Here is the snippet for my Share To Twitter button. Could you help me see if I missed out on anything? Thanks

```swift
    @objc func shareToTwitter() {
        print("Twitter pressed")
        if (Twitter.sharedInstance().sessionStore.hasLoggedInUsers()) {
            // App must have at least one logged-in user to compose a Tweet
            let composer = TWTRComposerViewController.emptyComposer()
            present(composer, animated: true, completion: nil)
        } else {
            // Log in, and then check again
            Twitter.sharedInstance().logIn { session, error in
                if session != nil { // Log in succeeded
                    let composer = TWTRComposerViewController.emptyComposer()
                    self.present(composer, animated: true, completion: nil)
                } else {
                    let alert = UIAlertController(title: "No Twitter Accounts Available", message: "You must log in before presenting a composer.", preferredStyle: .alert)
                    
                    let okAction = UIAlertAction(title: "Ok", style: .default, handler: { _ in
                        alert.dismiss(animated: true, completion: nil)
                    })
                    
                    alert.addAction(okAction)
                    
                    self.present(alert, animated: false, completion: nil)
                }
            }
        }
    }
```

**Comment by JacobJT** [comment]
I use the `TWTRComposer` instead of `TWTRComposerViewController`.  Try `let composer = TWTRComposer()` instead of `let composer = TWTRComposerViewController.emptyComposer()`, and `composer.show(from: self)` instead of `self.present(composer, animated: true, completion: nil)`

**Comment by sushinoya** [comment]
@JacobJT Thanks for the quick reply. That did not change the behaviour though :/. Clicking on the button opens the Twitter app where Twitter asks me to authorise my iOS app to read tweets etc. Then when I select "Connect", I am redirected back to my app. Pressing the button again just repeats the same thing (i.e Twitter app launches and I am asked for authorising my iOS app again)

**Comment by JacobJT** [comment]
@sushinoya Which block is executing? I imagine the first if?

I'm not sure what else to try. My displayTweet function just does what I put above, except it sets the text and url.  I had the behavior you're experiencing until wrapping that in the if block to check for hasLoggedInUsers and to sign in if there aren't any.

**Comment by sushinoya** [comment]
@JacobJT do you mind if I see your code for displayTweet?

**Comment by JacobJT** [comment]
```
        let composer = TWTRComposer()
        composer.setText(<My Text>)
        composer.setURL(<My URL>)
        composer.show(from: self) { result in
            if( result == .done) { print("Successfully composed Tweet") }
            else { print("Must have cancelled...") }
        }
```

**Comment by sushinoya** [comment]
After a bit of debugging (a commented out everything inside the displayTweet method), I realised that it is this line `Twitter.sharedInstance().logIn` that is causing the loop. 

After that neither the `if( session != nil )` condition nor the `else` condition are executed

**Comment by JacobJT** [comment]
Try reverting to the previous version, I've seen a lot of comments about it being less buggy. I only had that experience when I was opening the TWTRComposer without checking if I had a logged in user first.  Once I added the line you mentioned, it worked fine. 

Only difference I see between what we're doing is that I'm using `TWTRTwitter` instead of `Twitter`, so that's my last suggestion.

**Comment by sushinoya** [comment]
I already am using an older version
```   
pod 'TwitterCore', '~> 3.0.3'
pod 'TwitterKit', '~> 3.2.2'
```

I don't have a bridging header though. I thought the pod should do that for the user

**Comment by JacobJT** [comment]
I don't use Cocoapods, i use Carthage. Perhaps CocoaPods handles that and it was only an instruction when not using pods?

**Comment by nick-sturrock** [comment]
Like you I'm using the Twitter Kit just for simple tweets and I had this exact issue also, until I implemented the openURL callback in the app delegate:

`- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
            options:(NSDictionary *) options
{
    [[Twitter sharedInstance] application:application openURL:url options:options];
    return YES;
}
`

Also note from [this article](https://github.com/twitter/twitter-kit-ios/wiki/Installation) that it's necessary to have a placeholder URL in the configuration of the twitter app in the app.twitter.com dashboard, otherwise the redirect back to your app doesn't happen correctly. Implementing both these points fixed the issue for me.

**Comment by sushinoya** [comment]
@nick-sturrock This fixed it for me. Thanks!

**Comment by JacobJT** [comment]
@nick-sturrock Does this placeholder need to be a valid deeplink to your app? Or any URL? Is it acceptable to just put my website link there or it meant to be like a backend server call letting me know the action took place?

**Comment by nick-sturrock** [comment]
Just any valid URL will do - they recommended http://placeholder.com in their example, which works for me.

**Comment by nickthedude** [comment]
Thanks the 

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary *) options { [[Twitter sharedInstance] application:application openURL:url options:options]; return YES; }


worked for me. Although the fist time through it comes back as a blank tweet composer.

**Comment by katejlee** [comment]
The above method accepts url which will work.
Better fix is to update callback URL on apps.twitter.com to add something like:
`twitterkit-<consumerKey>://` 

And instead of returning `YES` on `openURL`, you can do normal:
`[[Twitter sharedInstance] application:application openURL:url options:options]`

This was announced Early May.
https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342

**Comment by ideastouch** [comment]
Yup, the only things needed is do folow Twitter documentation and add the function below, a simple copy paste:
```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
     return TWTRTwitter.sharedInstance().application(app, open: url, options: options)
}
```
