### ISSUE TITLE
Error in present Image, video on iphone X

### ISSUE THREAD

**Issue by HieuLsw** [twitter/twitter-kit-ios#50]
One line summary of the issue here.
I using twitterkit ver 3.3 and twittercore ver 3.1

In iphone X, when i click one item in timeline (video or image) the close button (X button) is over and under the status bar as attached image.
Can some one help me ?
![simulator screen shot - iphone x - 2018-04-02 at 11 35 09](https://user-images.githubusercontent.com/1675478/38183351-f9556b2a-3669-11e8-911f-12fdd43602ad.png)

**Comment by jessedijkstra** [comment]
Even less clear when the menu is white:
![picture 35](https://user-images.githubusercontent.com/226130/38504658-88633b70-3c15-11e8-87ca-94d610497d7b.jpg)

**Comment by kaylagalway** [comment]
I have the same issue - any one working on this? It results in having to force quit the app, since you can’t close the presented viewcontroller that is displaying the photo.

**Comment by tacoroot** [comment]
i try but 🤷🏻‍♂️ 
If I find a solution I will publish here 🙂

**Comment by kaylagalway** [comment]
I opened a PR for this: https://github.com/twitter/twitter-kit-ios/pull/56

**Comment by MatthewpHarding** [comment]
We are having this issue too for our high profile client. Can we please take a look at this PR and get it into the next release asap.
Thanks guys

**Comment by kaylagalway** [comment]
@MatthewpHarding I tweeted at them and was told they are including a fix for this when they release the next and last updated version of Twitterkit, but there is no estimation on when that will be. Could be soon, could be a few months.

**Comment by walsht** [comment]
Anyone know how to change the color of the media nav bar or close button.  I have tried everything, but still showing black on black.

**Comment by alexpersian** [comment]
@kaylagalway do you happen to have a link to their response?

Apple is updating their review guidelines in July, and if this iPhone X issue isn't fixed within TwitterKit by then apps that use this SDK will start to be rejected. Source: App Store engineer at WWDC.

**Comment by alexpersian** [comment]
Thanks for the info @kaylagalway

**Comment by kaylagalway** [comment]
Np @alexpersian - good luck

**Comment by katejlee** [comment]
There will be last release in next few days, and it includes PR by @kaylagalway. Thank you everyone.
