### ISSUE TITLE
Pod install fail. 

### ISSUE THREAD

**Issue by dongshuju** [twitter/twitter-kit-ios#52]
Pod install fail. 
Installing TwitterCore (3.1.0)
Installing TwitterKit (3.2.2)
[!] Error installing TwitterKit
[!] /usr/bin/curl -f -L -o /var/folders/gh/mz0gcm392rzf67m6nwdy90900000gn/T/d20180404-4557-xg94o3/file.zip https://ton.twimg.com/syndication/twitterkit/ios/3.2.2/TwitterKit.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to ton.twimg.com port 443: Operation timed out

**Comment by dongshuju** [comment]
Anyone has same issue?

**Comment by CG-Kerr** [comment]
之前一直没成功,看到你这个问题后又试了试成功了竟然,你做twitter的登录没?能唤起客户端吗?我这边一直是网页登录,想请教下在哪设置的

**Comment by CG-Kerr** [comment]
496547676方便的话q我

**Comment by a-playboy-me** [comment]
@dongshuju This article may help you fix this error.
https://www.jianshu.com/p/598bf279b2d6

**Comment by katejlee** [comment]
This doesn't seem to be TwitterKit issue since we updated to 3.3.0 as we opensourced on github.
