### ISSUE TITLE
Repo ignored by maintainers

### ISSUE THREAD

**Issue by JacobJT** [twitter/twitter-kit-ios#58]
Widely used repo for major social platform doesn't receive updates or acknowledgment for plethora of issues

### Expected behavior

Project maintainers respond to issues, fix bugs in a timely manner

### Actual behavior

Issues go ignored and bugs that should be a simple fix remain in the production release

### Steps to reproduce the behavior

Try to use the SDK and experience issues, report the issues.

**Comment by kevenbauke** [comment]
Regarding this topic :( They will stop the support for this SDK after October.

https://blog.twitter.com/developer/en_us/topics/tools/2018/discontinuing-support-for-twitter-kit-sdk.html

**Comment by JacobJT** [comment]
Ahh they took the ol' "We wanted to save money and let the community do it for us" approach with this and it hasn't worked out... That's a shame.

**Comment by bbookman** [comment]
What?  This makes no sense at all

**Comment by bbookman** [comment]
Goodbye twitter login for my app in development now

**Comment by dafurman** [comment]
If you're just using this for login authentication, switch to using https://github.com/OAuthSwift/OAuthSwift. It's pretty easy to set up and allow for greater flexibility of OAuth services.

**Comment by JacobJT** [comment]
Anybody have a simple, maintained, and not-soon-to-be-trashed solution if the only functionality you want is a social share button?

**Comment by pasevin** [comment]
@dafurman looks like OAuthSwift not hasn't been updated for months as well. You think it's solid?

**Comment by dafurman** [comment]
Sure, at the end of the day OAuth is still supported by Twitter and that’s certainly not going anywhere, despite this repo not being maintained.
Plus, even if OAuthSwift were to have issues, all it does is remove the boilerplate from OAuth, which wouldn’t be hard to write yourself. There’re plenty of tutorials on it as well if necessary. I just suggest it to save a bit of time.

**Comment by evansobkowicz** [comment]
We've accepted the open PRs and included them in the recent [3.4.0 release](https://cocoapods.org/pods/TwitterKit). Please see the [blog post](https://blog.twitter.com/developer/en_us/topics/tools/2018/discontinuing-support-for-twitter-kit-sdk.html) referenced above for more info about the discontinuation of development on TwitterKit.

**Comment by JacobJT** [comment]
Thanks for the update. Will a new release be added to GitHub so we can review the changes that have been made?

Also, installation instructions could use a quick update: 
https://github.com/twitter/twitter-kit-ios/wiki/Installation

>Note: From v3.4.0 and higher, please make sure to remove all references to TwitterShareExtensionUI in your project settings if they are not already removed by Cocoapods. You may notice a TwitterShareExtensionUI resource bundle file in the "Build Phases" section of your project section, please remove this.

This is also an issue with Carthage, not doing so keeps the dozens of line of output complaining about duplicate files.

**Comment by rajul-arora** [comment]
@JacobJT I updated the Wiki with a similar note for carthage. Thanks for catching that!

**Comment by evansobkowicz** [comment]
Hi @JacobJT,

You can find the most recent GitHub release here: https://github.com/twitter/twitter-kit-ios/releases/tag/v3.4.0.
