### ISSUE TITLE
Migration from previous version?

### ISSUE THREAD

**Issue by zapjonny** [twitter/twitter-kit-ios#6]
First, a quick update from previous framework version and the app wouldn't compile. You should probably leave some migration instructions in the release notes?

Second, you might want to update the boilerplate text for new issues, it says this is the Android repo:

This form is for reporting issues in the Twitter Kit Android library. For all other developer questions/issues about Twitter please visit [Twitter Community](https://twittercommunity.com/).

**Bug Report**

We work constantly to fix bugs, tweak functionality and improve device support. Providing detailed feedback will help us to quickly resolve your issue.

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
* * Expected behavior:
* * iOS Version (eg. iOS 10.2):
* * iOS Device Model (eg. iPhone 6):
* * TwitterKit/TwitterCore Version Number:

* **Feature Request**
*
* If you have anything you'd like to contribute, we recommend discussing it with the core team before writing it.
*
* * Describe feature in as much detail as possible:
* * Include sample usage where appropriate:

**Comment by zapjonny** [comment]
Btw I was using 3.2.2 (I think), Swift, and the only real change I had to do was change the main class name from Twitter to TWTRTwitter a few times.

**Comment by katejlee** [comment]
Thank you for suggestions. We've updated issue template, and will be released soon along with updated TwitterKit.
