### ISSUE TITLE
TwitterKit provides Application-only authentication? 

### ISSUE THREAD

**Issue by charleslima** [twitter/twitter-kit-ios#60]
How can I make an Application-only authentication? 

My app there is no user session, I only need to show a hashtag search timeline, but I'm limited of 180 request por 15 minutes, I noticed that I can obtain 450 request per 15 minutes if I use Application-only authentication, how can I do it using TwitterKit?

**Comment by andypiper** [comment]
Twitter Kit does not support application-only authentication. 

Per https://github.com/twitter/twitter-kit-ios/wiki/Log-In-With-Twitter you can either have a user session, or use guest authentication, but in both cases you'll be rate limited at the 180/15 min level.
