### ISSUE TITLE
TwitterKit Crash on query https://api.twitter.com/1.1/users/search.json

### ISSUE THREAD

**Issue by clintonhbuie** [twitter/twitter-kit-ios#64]
For requests through the TwitterKit client, most succeed just fine.  However, whenever it's necessary to query for Twitter Handles, the application crashes when trying to instantiate a url request.  Something seems to be wrong with the generation of Headers for the request.

<img width="438" alt="screen shot 2018-05-21 at 10 24 41 pm" src="https://user-images.githubusercontent.com/38666273/40343693-f9362898-5d45-11e8-9214-f8959ef316f7.png">
<img width="738" alt="screen shot 2018-05-21 at 10 24 20 pm" src="https://user-images.githubusercontent.com/38666273/40343695-fad9a026-5d45-11e8-8330-8203e75ba9a2.png">

**Comment by rajul-arora** [comment]
Hi @clintonhbuie, I tried reproducing your issue with this code snippet: 

```
        let client = TWTRAPIClient.withCurrentUser()

        let query = "q=@rajularora"
        let api = "https://api.twitter.com/1.1/users/search.json?\(query)"
        var clientError: NSError?
        let request = client.urlRequest(withMethod: "GET", urlString: api, parameters: nil, error: &clientError)
        let task = URLSession.shared.dataTask(with: request) { (data, response, error) in
            if let error = error {
                debugPrint(error)
            } else if let data = data, let json = try? JSONSerialization.jsonObject(with: data, options: JSONSerialization.ReadingOptions.allowFragments) {
                debugPrint(json)
            }
        }

        task.resume()
    }
```

I wasn't able to reproduce your issue, the only major difference between my test is the parameters you are encoding, which I cannot see given the code snippet you provided.

Although, when I look at the `api` variable in the code snippet you provided, it looks like you might have an extraneous `=` or you are missing a parameter there.
