### ISSUE TITLE
Cannot add account in demo app, getting 401 error

### ISSUE THREAD

**Issue by zapjonny** [twitter/twitter-kit-ios#7]
・3.3.0

・Added consumer key/secret to Config.xcconfig like this:

TWITTER_CONSUMER_KEY = adasdassdas
TWITTER_CONSUMER_SECRET = 443fs4ff

(actually using real values)
I was not sure if Config.xcconfig needs quotes around the values, tried with/without, neither works.

・Actions taken in app:

1. Account button top right
2. Add Account
3. Log in with Twitter

Getting alert:

> Error - Request failed: unauthorized (401) - Dismiss

Device: iPhone SE, iOS 11.0

**Comment by zapjonny** [comment]
By manually setting consumer key/secret in Info.plist (as opposed to using `$(TWITTER_CONSUMER_KEY)` etc) things started working. I guess there is something wrong with the use of the Config.xcconfig file.

**Comment by katejlee** [comment]
It could be possible that the Config.xcconfig file is not properly read from your project file on XCode. Either way, most important thing is that your consumer key and secret is working. `$(TWITTER_CONSUMER_X)` is there to reduce amount of duplicate you have across config file. Closing the ticket for you seem to have other work way around it.
