### ISSUE TITLE
TWTRComposer image loop and crash on iPhone X

### ISSUE THREAD

**Issue by DimMad** [twitter/twitter-kit-ios#72]
Hello everyone,

I am using the composer for posting some text and an image (screenshot from device). On iPhone X that is causing the app to freeze, high CPU usage, and eventual background time limit crash. After playing around with images I realized that the problem was the aspect ratio of the image. The moment the image passes the 9:16 something is going wrong with the constraints of the UIImage handling in the composer (TWTRComposerViewController is used).

### Expected behavior

The composer dialog with the expected text and image should appear

### Actual behavior

The application freezes (iPhone X only), high CPU usage, background time limit reached and app crashes.

### Steps to reproduce the behavior

 - Take any screenshot with iPhone X and pass it in the composer
 - Take any image size doesn't seem to matter and play with its dimensions rebuilding and trying it in the composer. Horizontal doesn't seem to matter but once the vertical aspect ratio goes out of the 9:16 trouble start.

**Comment by djmason9** [comment]
I am having this exact same issue on iphone X

**Comment by nickthedude** [comment]
same issue. will try workaround.

**Comment by rajul-arora** [comment]
Your PR is included for the next TwitterKit release. Thanks for being patient!
