### ISSUE TITLE
ViewController's deinit never called after passing the VC to logIn(with:completion:)

### ISSUE THREAD

**Issue by horita-yuya** [twitter/twitter-kit-ios#8]
I'm developing my app, using multi windows. Simply, assuming that there are two windows, mainWindow and VideoPlayerWindow. The VideoPlayerWindow has higher window level than mainWindow.

After I call TWTRTwitter.sharedInstance.logIn(with:completion:), passing it the VideoPlayerWindow.rootViewController, the viewController's deinit never called, or captured.

What is the cause of this?
I'm using 
Device: iPhoneX
iOS v11.1
Xcode 9.2
TwitterKit v3.3.0.

Thank you.

**Comment by katejlee** [comment]
This has been merged internally and will be added as part of the next TwitterKit release!
