### ISSUE TITLE
XCode 10 GM and Swift 4.2 Compiler Warning

### ISSUE THREAD

**Issue by jlaws** [twitter/twitter-kit-ios#95]
Building the TwitterCore cocoapod shows compiler warnings.

### Expected behavior

The cocoapod should build with no warnings.

### Actual behavior

```
/Users/joelaws/Workspace/kratos/Pods/TwitterCore/iOS/TwitterCore.framework/Modules/module.private.modulemap:1:29: Private submodule 'TwitterCore.Private' in private module map, expected top-level module
/Users/joelaws/Workspace/kratos/Pods/TwitterCore/iOS/TwitterCore.framework/Modules/module.private.modulemap:1:29: Rename 'TwitterCore.Private' to ensure it can be found by name
```

### Steps to reproduce the behavior

1. Download XCode 10 GM
2. Setup a project and Podfile that depends on TwitterCore
3. Compile the main target and the TwitterCore cocoapod
4. see the build warnings

**Comment by AlexGingell** [comment]
Has anyone managed to obtain a version of TwitterKit v3.4.0 that is error free?  I have checked many forks and branches and cannot see any error-free versions which compile error-free and produce no issues.  If it is not this issue it is
> Umbrella header for module 'TwitterCore' does not include header 'TWTRColorUtil.h'

**Comment by JacobJT** [comment]
@rajul-arora @evansobkowicz 

I don't have any experience working with frameworks or I'd make my own PR, but I wouldn't even know how to confirm it works or not,

Any chance we can get implementations to fix this error (and subsequent TWTRColor.h issue) similar to these commits from one of the forks?

Remove the private module:
cb75d55a7b8d42e107658250d3417bd64678e973

Add TWTRColor.h to the public module map:
dc4b422d5b196e4aa420e6b28aad051afac2974b

Dunno if this one is required, but was done right after the others, unlink libTwitterCore in TwitterKit.framework:
de5674fe5162eb3f541389be1cda64a83551a20f

Been lookin' forward to the day we have a warning free project to compile for years, and this is one of the last couple things preventing that.

**Comment by jlaws** [comment]
Posted on the twitter dev forum [here](https://twittercommunity.com/t/xcode-10-gm-and-swift-4-2-compiler-warning/113823)

**Comment by jlaws** [comment]
I removed the Twitter SDK from my cocoapods and no longer have this issue

https://blog.twitter.com/developer/en_us/topics/tools/2018/discontinuing-support-for-twitter-kit-sdk.html

**Comment by npu3pak** [comment]
Got some working solution. It fixed all TwitterCore related warnings for me.
https://gist.github.com/npu3pak/108d8332a774289c08472d6fd85a1bbb
